[project]
name = "todo-list-flet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet[all]>=0.28.3",
    "pydantic>=2.12.4",
    "sqlalchemy>=2.0.44",
]
